---
environment_repo: &environment_repo git@github.com:your-org/your-repo.git
environment_dir: &environment_dir azure/environments
environment_name: &environment_name mycoolenvironment
system_domain: &sys_domain mycoolenvironment.example.com
devbox_username: &devbox_username myuser
git_email: &git_email my_github_email@example.com
git_name: &git_name myuser
github_key: &github_key {{github-key}}
worker_tag: &worker_tag []
azure_region: &azure_region "West US"
azure_subscription: &azure_subscription {{azure_subscription}}
azure_tenant_id: &azure_tenant_id {{azure_tenant_id}}
azure_client_id: &azure_client_id {{azure_client_id}}
azure_client_secret: &azure_client_secret {{azure_client_secret}}
aws_shared_dns_access_key: &aws_shared_dns_access_key {{aws-shared-dns-access-key}}
aws_shared_dns_access_secret: &aws_shared_dns_access_secret {{aws-shared-dns-access-secret}}
aws_route53_zone_id: &aws_route53_zone_id Z1OE08QT9BJFFU  # this is cf-app.com

groups:
- name: bootstrap-azure
  jobs:
  - bootstrap-environment
  - setup-devbox-upload-bosh-yml
- name: deploy-cf-azure
  jobs:
  - deploy-bosh-generate-upload-deployment-ymls
  - deploy-mysql
  - deploy-cf
  - deploy-diego
- name: destroy-cf-azure
  jobs:
  - destroy-bosh-deployments
  - destroy-bosh-director
  - destroy-azure-resource-group

resources:
  - name: azure_environments
    type: git
    source:
      uri: *environment_repo
      branch: master
      private_key: *github_key
  - name: toolsmiths-shared-scripts
    type: git
    source:
      uri: https://github.com/pulkitpivotal/toolsmiths-shared-scripts
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEogIBAAKCAQEAwxWUDONkXcQM8TTYrGcdrmcslINPDhk9u8Lreez2dTGnDgoS
        5HvJH1ZFTdKx0hrKD8tSmrD1i1tJQcJz7Z41GeIVrzosY5ts1gVkFqAdKKTA+fsR
        Y8elNETfN4yLe3EbgB0e8AyQ9g0v0Kk5W/DUF+VpI5rKI9yvUzDm0bE9IpveR5ja
        Wo6YnvaXBij+gTPhYfom1lJq9MwJpllBu89nd5ZAOqZKqK6pnfj5bVMAM23+LfUX
        LNjypzSqQpaOvrZe1ACbN4n9egNEgwQz7QukZDXyiF3SPAvZYoXeKr/dOc2QZcQS
        Yyj+29FuyYkBahk7tpwTGSTG/LzFEJxQunA6eQIDAQABAoIBAGPEaU6eC/oYBTZl
        /FlO8tL6WMYq0Qc4yWV4rcxQ70nH9tMrO7Y1yAmKqS6/jckRgjzJkpkh3rFCIhjL
        RVZEDowKH2TZr1HRbruVTjZz8/WRLE+rop0QwOAWSMGz0rFyisneGrBQ/OGYpNdl
        c7wdUZpW7IoU40Or3M4CuEiNB+LmRsL0t7tBDSu5KE2Ec1n46auC4j9tTEJYtsv9
        XJ41+qyph1lXgt4wNfJ8ciBjs25nQPvCYUJoAtb0UxU+E80xPmJ6b34V01EEohDZ
        sAoBDVBLe4zBPWibZsUIRKFYyf5OMmr8+Iy2T5DV0SclCvZTpfS4KbOEI8hYr6a2
        pn3FIgECgYEA68qf/eZJdqc0Sn3oY6jtVkW5RzKjQjY21L9enJVFXelObdj/vZER
        n4HclENGK7XFGvi9nkcv746JoomiPkiyFzZO6gEuEi2vDaG5Hf55fevALWwsWNcU
        UpvZjuqdfcsXwUdq8KsVjM7trEUVyqJmgQt3wen2I42u9FxWPK81XLECgYEA083R
        dVbnLicBiuZwsB8YKtYCQggVXCL4nbE0kXKIv1LLC4X8fnHPyUmGOX+NhNMAyr4o
        fmP8QiJcERcT9XNR8pceeZJ3CgMn645/alnc+o5kBSWBeZBIxUC1GJRjLgkuuwlV
        KdVK/OsWheTLzOPBi4Xpo0A/O9tb9//X3bAIjEkCgYBRroTUIOWMHAoqUAmkFI37
        V/YCKxGRS1SdSJoO5kr8aGkJ9qVJVyritcri9ZcmZzabzFVrsj9x3k/hpYo1x1si
        XWbi+3upQngk4cROFqyhqXyOf62xLPjWUTUBpFbgj+1vwDzUmH/Dop+FEP2mj7Gw
        vHdFDrZ8xIU6E46wQQXcUQKBgCqyE6YetY11KXdxiofGTN3dtCjRblTba9iF7z3e
        o7hFnU6eXM60bJl768XNc56x1jgIaytHRoOiX4LGbyyMaZmIYwlIwBxRlIuEdyTe
        JpCPgZQUAmyZ7EFvENJ6nx+ZlET51aQQLgSb8zdcbsTHqK1Sek2BVv3e80Qj28UB
        hkeZAoGAe1QZw0I7dQQrtkm+SH26SjH9FFgIyBYqM2eFkVV12PLV+UEU8O126mTs
        dB3hZ13iNjsTBjyiGtKw+8QpHxwBL7smyjnVYBidzGdjtZcmfvEi1q1HrlhCT8sc
        ZdqXCXgiy3+kyzCVXS6jZB/FELHymBe7R2cYw6FxARII7ECw4IQ=
        -----END RSA PRIVATE KEY-----

jobs:
  - name: bootstrap-environment
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
    - task: create-environment
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        outputs:
        - name: environment
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_terraform.sh -d ${ENV_DIR}/${ENV_NAME} apply"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir
        DEVBOX_USERNAME: *devbox_username
        AZURE_REGION: *azure_region
        AZURE_SUBSCRIPTION: *azure_subscription
        AZURE_TENANT_ID: *azure_tenant_id
        AZURE_CLIENT_ID: *azure_client_id
        AZURE_CLIENT_SECRET: *azure_client_secret
        AWS_SHARED_DNS_ACCESS_KEY: *aws_shared_dns_access_key
        AWS_SHARED_DNS_ACCESS_SECRET: *aws_shared_dns_access_secret
        AWS_ROUTE53_ZONE_ID: *aws_route53_zone_id
        GIT_EMAIL: *git_email
        GIT_NAME: *git_name
        SYSTEM_DOMAIN: *sys_domain
      ensure:
        put: azure_environments
        params:
          repository: environment
          rebase: true

  - name: setup-devbox-upload-bosh-yml
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
        passed: [bootstrap-environment]
    - task: setup-devbox-upload-bosh-yml
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_setup_dev_box.sh azure_environments/${ENV_DIR}/${ENV_NAME}"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir

  - name: deploy-bosh-generate-upload-deployment-ymls
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
    - task: deploy-bosh-and-generate-ymls
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        outputs:
        - name: environment
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_deploy_bosh_generate_ymls.sh $ENV_DIR/$ENV_NAME"]
      params:
        GIT_EMAIL: *git_email
        GIT_NAME: *git_name
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir
    - put: azure_environments
      params:
        repository: environment
        rebase: true

  - name: deploy-mysql
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
        passed: [deploy-bosh-generate-upload-deployment-ymls]
        trigger: true
    - task: deploy-mysql
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh deployment ~/mysql.yml && bosh -n deploy'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir

  - name: deploy-cf
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
        passed: [deploy-mysql]
        trigger: true
    - task: deploy-cf
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh deployment ~/cf.yml && bosh -n deploy'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir

  - name: deploy-diego
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
        passed: [deploy-cf]
        trigger: true
    - task: deploy-diego
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh deployment ~/diego.yml && bosh -n deploy'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir

  - name: destroy-bosh-deployments
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
    - task: destroy-diego-deployment
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh -n delete deployment diego --force'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir
    - task: destroy-cf-deployment
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh -n delete deployment cf --force'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir
    - task: destroy-mysql-deployment
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh -n delete deployment mysql --force'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir

  - name: destroy-bosh-director
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
        passed: [destroy-bosh-deployments]
    - task: destroy-bosh-director
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_devbox_ssh.sh azure_environments/$ENV_DIR/$ENV_NAME 'bosh-init delete ~/bosh.yml'"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir

  - name: destroy-azure-resource-group
    build_logs_to_retain: 50
    serial: true
    plan:
    - aggregate:
      - get: toolsmiths-shared-scripts
      - get: azure_environments
        passed: [destroy-bosh-director]
    - task: destroy-azure-resource-group
      config:
        platform: linux
        image: docker:///cftoolsmiths/deploy-cf-azure
        inputs:
        - name: toolsmiths-shared-scripts
        - name: azure_environments
        outputs:
        - name: environment
        run:
          path: /bin/bash
          args: ["-c", "toolsmiths-shared-scripts/azure/ci_terraform.sh -d ${ENV_DIR}/${ENV_NAME} destroy"]
      params:
        ENV_NAME: *environment_name
        ENV_DIR: *environment_dir
        DEVBOX_USERNAME: *devbox_username
        AZURE_REGION: *azure_region
        AZURE_SUBSCRIPTION: *azure_subscription
        AZURE_TENANT_ID: *azure_tenant_id
        AZURE_CLIENT_ID: *azure_client_id
        AZURE_CLIENT_SECRET: *azure_client_secret
        AWS_SHARED_DNS_ACCESS_KEY: *aws_shared_dns_access_key
        AWS_SHARED_DNS_ACCESS_SECRET: *aws_shared_dns_access_secret
        AWS_ROUTE53_ZONE_ID: *aws_route53_zone_id
        GIT_EMAIL: *git_email
        GIT_NAME: *git_name
        SYSTEM_DOMAIN: *sys_domain
      ensure:
        put: azure_environments
        params:
          repository: environment
          rebase: true
